---
- name: Create data folder
  file:
    path: "{{ taskd_data_location }}"
    owner: "{{ taskd_user }}"
    group: "{{ taskd_group }}"
    mode: 0755
    state: directory

- name: Set permanent TASKDDATA variable
  lineinfile:
    dest: /etc/profile
    line: "export TASKDDATA={{ taskd_data_location }}"
    regexp: "^export TASKDDATA="
    state: present
    insertafter: eof
  when: ansible_connection != 'docker'

- name: Init datafolder
  command: /usr/local/bin/taskd init
  args:
    creates: "{{ taskd_data_location }}/config"
  environment:
    TASKDDATA: "{{ taskd_data_location }}"
  when: not taskd_installed.stat.exists

- name: Create config file for taskd
  template:
    src: taskd_config.j2
    dest: "{{ taskd_data_location }}/config"
    owner: "{{ taskd_user }}"
    group: "{{ taskd_group }}"
  when: not taskd_installed.stat.exists

- block:
    - name: Copy selfsigning vars file to location
      template:
        src: ssl_vars.j2
        dest: "{{ taskd_install_location }}/pki/vars"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"

    - name: Run generate cert script
      command: "{{ taskd_install_location }}/pki/generate"
      args:
        creates: "{{ taskd_install_location }}/pki/ca.key.pem"
        chdir: "{{ taskd_install_location }}/pki/"
      environment:
        TASKDDATA: "{{ taskd_data_location}}"
      register: taskd_server_certs

    - name: Copy generated certs to data location
      copy:
        src: "{{ taskd_install_location }}/pki/{{ item }}"
        dest: "{{ taskd_data_location }}/{{ item }}"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"
        remote_src: true
      with_items:
        - server.cert.pem
        - server.key.pem
        - server.crl.pem
        - ca.cert.pem
        - ca.key.pem
      when: taskd_server_certs.changed

  when: taskd_selfsigned == true
