---
dist: trusty
language: python
sudo: required
cache:
  pip: true

env:
  global:
    - fast_finish: true
    - MAKEFLAGS="-j 2"
    - PIP='pip'
    - ANSIBLE_VERSION='ansible'
    - SCENARIO=default

matrix:
  include:
    - python: '2.7'
      env: SCENARIO=legacy ANSIBLE_VERSION='ansible>=2.2.0,<2.3.0'  # 2.2.x security only
    - python: '2.7'
      env: SCENARIO=legacy ANSIBLE_VERSION='ansible>=2.3.0,<2.4.0'  # 2.3.x bugs and security
    - python: '2.7'
      env: ANSIBLE_VERSION='ansible>=2.4.0,<2.5.0'  # 2.4.x bugs and security
    - python: '2.7'
      env: ANSIBLE_VERSION='--pre ansible'  # Pre-releases
    - python: '2.7'
      env: ANSIBLE_VERSION='git+https://github.com/ansible/ansible.git@devel'  # DEVEL
    - python: '3.5'
      env: SCENARIO=python3 PIP='pip3'

  allow_failures:
    - python: '2.7'
      env: ANSIBLE_VERSION='git+https://github.com/ansible/ansible.git@devel'  # DEVEL

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install --only-upgrade docker-ce -y

install:
  - $PIP install $ANSIBLE_VERSION molecule docker-py

script:
  - ansible --version
  - molecule test --debug --scenario-name $SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_failure: change
    on_success: never
