---
- name: Create data folder
  file:
    path: "{{ taskd_data_location }}"
    owner: "{{ taskd_user }}"
    group: "{{ taskd_group }}"
    mode: 0755
    state: directory

- name: Init datafolder
  command: "taskd init"
  args:
    creates: "{{ taskd_data_location }}/config"
  environment:
    TASKDDATA: "{{ taskd_data_location }}"
  become: yes
  become_user: "{{ taskd_user }}"

- name: Create config file for taskd
  template:
    src: taskd_config.jinja2
    dest: "{{ taskd_data_location }}/config"
    owner: "{{ taskd_user }}"
    group: "{{ taskd_group }}"

- block:
    - name: Copy selfsigning vars file to location
      template:
        src: ssl_vars.jinja2
        dest: "{{ taskd_install_location }}/pki/vars"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"

    - name: Run generate cert script
      shell: ./generate
      args:
        creates: "{{ taskd_install_location }}/pki/ca.key.pem"
        chdir: "{{ taskd_install_location }}/pki/"
      become: yes
      become_user: "{{ taskd_user }}"
      register: taskd_server_certs

    - name: Copy generated certs to data location
      copy:
        src: "{{ taskd_install_location }}/pki/{{ item }}"
        dest: "{{ taskd_data_location }}/{{ item }}"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"
        remote_src: yes
      with_items:
        - server.cert.pem
        - server.key.pem
        - server.crl.pem
        - ca.cert.pem
        - ca.key.pem
      when: taskd_server_certs.changed

  when: taskd_selfsigned == true