---
- include_tasks: init-variables.yml

- include_tasks: install-taskd/main.yml
  when: (not taskd_installed.stat.exists) or
        (taskd_version not in taskd_installed_version.stdout)

- include_tasks: manage-taskd/manage.yml
  when: taskd_organizations is defined and taskd_users is defined
