---
- include: load-variables.yml

- name: Check if taskd is installed
  stat:
    path: /usr/local/bin/taskd
  register: taskd_installed

- name: Register installed taskd version
  command: /usr/local/bin/taskd --version
  register: taskd_installed_version
  changed_when: false
  when: taskd_installed.stat.exists

- block:
    - include: prerequisite.yml
      vars:
        state: present

    - include: install-taskd/main.yml

    - include: prerequisite.yml
      vars:
        state: absent

  when: (not taskd_installed.stat.exists) or
        (taskd_version not in taskd_installed_version.stdout)

- include: manage-taskd/main.yml
