---
- block:
    - name: PREREQUISITE | Install Yum default packages
      yum:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ taskd_yum_packages }}"

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- block:
    - name: PREREQUISITE | Install Apt default packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ taskd_apt_packages }}"

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'