---
- block:
    - set_fact:
        taskd_yum_packages: "{{ taskd_yum_packages }} + [ 'python-urllib3', 'pyOpenSSL', 'python-ndg_httpsclient', 'python-pyasn1' ]"
      when: ansible_distribution_major_version|int <7

    - name: PREREQUISITE | Install Yum default packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items: "{{ taskd_yum_packages }}"

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

# TODO: Make prettier, load var files?
- block:
    - set_fact:
        taskd_apt_packages: "{{ taskd_apt_packages }} + [ 'python-urllib3', 'python-openssl', 'python-ndg-httpsclient', 'python-pyasn1' ]"
      when: (ansible_distribution == 'Debian' and ansible_distribution_version|int == 7) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= 14.04)

    - set_fact:
        taskd_apt_packages: "{{ taskd_apt_packages | replace('libgnutls-dev', 'libgnutls28-dev') }}"
      when: ansible_distribution == 'Debian' and ansible_distribution_version|int >= 8

    - name: add backports repository
      apt_repository:
        repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: present
      when: ansible_distribution == 'Debian' and ansible_distribution_version|int == 7

    - name: PREREQUISITE | Install Apt default packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ taskd_apt_packages }}"

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'