---
- block:
    - set_fact:
        taskd_yum_packages: "{{ taskd_yum_packages }} + [ 'python-urllib3', 'pyOpenSSL', 'python-ndg_httpsclient', 'python-pyasn1' ]"
      when: ansible_distribution_major_version|int <7

    - name: PREREQUISITE | Install Yum default packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items: "{{ taskd_yum_packages }}"

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- block:
    - name: PREREQUISITE | Install Apt default packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ taskd_apt_packages }}"

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'