---
- name: SETUP | Create data folder
  file:
    path: "{{ taskd_data_location }}"
    owner: "{{ taskd_user }}"
    group: "{{ taskd_group }}"
    mode: 0755
    state: directory

- name: SETUP | Init datafolder
  command: "taskd init"
  become: yes
  become_user: "{{ taskd_user }}"

- block:
    - name: SETUP | Copy selfsigning vars file to location
      template:
        src: ssl_vars.jinja2
        dest: "{{ taskd_install_location }}/pki/vars"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"

    - name: SETUP | Run generate cert script
      shell: ./generate
      args:
        chdir: "{{ taskd_install_location }}/pki/"
      become: yes
      become_user: "{{ taskd_user }}"

    - wait_for:
        path: "{{ taskd_install_location }}/pki/{{ item }}"
      with_items:
        - server.cert.pem
        - server.key.pem
        - server.crl.pem
        - ca.cert.pem
        - ca.key.pem

    - name: SETUP | Copy generated certs to data location
      copy:
        src: "{{ taskd_install_location }}/pki/{{ item }}"
        dest: "{{ taskd_data_location }}/{{ item }}"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"
        remote_src: yes
      with_items:
        - server.cert.pem
        - server.key.pem
        - server.crl.pem
        - ca.cert.pem
        - ca.key.pem

  when: taskd_selfsigned == true

- name: SETUP | Create config file for taskd
  template:
    src: taskd_config.jinja2
    dest: "{{ taskd_data_location }}/config"
    owner: "{{ taskd_user }}"
    group: "{{ taskd_group }}"