---
- name: Create users and certs folder
  file:
    path: "{{ taskd_user_cert_location }}"
    owner: "{{ taskd_user }}"
    group: "{{ taskd_group }}"
    mode: 0755
    state: directory

- name: Check for user.conf existence
  stat:
    path: "{{ taskd_user_conf_location }}/users.conf"
  changed_when: false
  register: taskd_user_conf

- name: Create users.conf when nonexisting
  file:
    path: "{{ taskd_user_conf_location }}/users.conf"
    owner: "{{ taskd_user }}"
    group: "{{ taskd_group }}"
    state: touch
  when: taskd_user_conf.stat.exists == false

- name: Create variable containing users.conf
  command: "cat {{ taskd_user_conf_location }}/users.conf"
  register: taskd_users_conf
  changed_when: false

- include: taskd-useradd.yml
  with_items: "{{ taskd_users }}"
  loop_control:
    loop_var: outer_item