---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint

platforms:
  - name: Centos7
    image: lansible/centos:7

  - name: Debian9
    image: lansible/debian:9

  - name: Debian8
    image: lansible/debian:8

  - name: Ubuntu1604
    image: lansible/ubuntu:16.04

provisioner:
  name: ansible
  options:
    vv: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: molecule/.ansible-lint

scenario:
  name: default

verifier:
  name: goss
  enabled: false
