---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: lxd

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: Taskserver-CentOS7
    alias: centos/7/amd64

  - name: Taskserver-CentOS6
    alias: centos/6/amd64

  - name: Taskserver-Debian9
    alias: debian/stretch/amd64

  - name: Taskserver-Debian8
    alias: debian/jessie/amd64

  - name: Taskserver-Ubuntu1804
    alias: ubuntu/bionic/amd64

  - name: Taskserver-Ubuntu1604
    alias: ubuntu/xenial/amd64

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

verifier:
  name: goss
  lint:
    name: yamllint
    options:
      config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

scenario:
  name: default
