---
- name: Converge
  hosts: all

  vars:
    taskd_organizations:
      - Public
    taskd_users:
      - name: First Last
        organization: Public

  roles:
    - role: ansible-role-taskserver
      taskd_ip_address: 127.0.0.1
