---
- name: Converge
  hosts: all

  vars:
    taskd_organizations:
      - Public
    taskd_users:
      - name: First Last
        organization: Public

  roles:
    - role: ansible-role-taskserver

  post_tasks:
    - name: Test taskd version
      shell: "taskd --version | grep -q '{{ taskd_version }}' && (echo 'Taskserver v{{ taskd_version }} installed'; exit 0) || (echo 'Taskserver not correct installed'; exit 1)"
      changed_when: false

    - name: Grab system Logs
      shell: "journalctl -xn || cat /var/log/messages || cat /var/log/syslog"
      environment:
        - PAGER: cat
      changed_when: false
      ignore_errors: true
